### ISSUE TITLE
Box hinter den Icons für besser Erkennung 

### ISSUE THREAD

**Issue by TeePlunder** [mediainterface/erkenntnis-des-tages#29]
Manche Icons sind in dieser Sichtweise nicht wirklich gut zu erkennen. Deswegen wäre eine etwas hellere Box, um diese Icons sehr hilfreich.

![image](https://github.com/mediainterface/erkenntnis-des-tages/assets/93575165/c2fbf7fb-4764-490b-9de5-34de71b863d5)

**Comment by cat-miller** [comment]
bin ich grad dran :)
